[tool.poetry]
name = "hexlet-code"
version = "0.1.0"
description = ""
authors = ["pestrukha <sturbauen@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.10"
flask = "^3.0.3"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
